const action_constants = {
	ADD_PROJECT: 'ADD_PROJECT',
	TOGGLE_NAV: 'TOGGLE_NAV',
	TOGGLE_CLOSE_BUTTON: 'TOGGLE_CLOSE_BUTTON',
	SET_ACTIVE_PROJECT_SCROLL: 'SET_ACTIVE_PROJECT_SCROLL',
	SET_SCROLL_POS: 'SET_SCROLL_POS',
	SET_SCROLL_HEIGHT: 'SET_SCROLL_HEIGHT',
	ANIMATE_LOGO: 'ANIMATE_LOGO',
}

export default action_constants; 